[package]
name = "lomak-py"
version = "0.1.0"
edition = "2018"
authors = [ "Aurelien Naldi <aurelien.naldi@gmail.com>" ]


[lib]
name = "lomak"
crate-type = ["cdylib"]

[dependencies]
lomak = { path = "../.." }

[dependencies.pyo3]
version = "0.7"
features = ["extension-module"]

